# Fraude detection model trainig workflow

 on:
  github:
    branches:
      only: main

jobs:

  # 1. Clone YOLOv5

  cloneYOLO:
    resources:
      instance-type: C4
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/ultralytics/yolov5.git

  # 2. Get Intalling requirement
  intallRequirement:
    resources:
      instance-type: C4
    needs:
      - cloneYOLO

    inputs:
      repo: cloneYOLO.outputs.repo

    uses: script@v1
      with:
        script: |-
          cd /yolov5
          pip install -r requirements.txt
      image: tensorflow/tensorflow:1.14.0-gpu-py3


  # 3. Trainning the model

  trainModel:
     resources:
       instance-type: P4000
     needs:
       - intallRequirement
     inputs:
       repo: cloneYOLO.outputs.repo
     outputs:
       checkPoints:
         type: dataset
         with:
           ref: yolo-check-point
     uses: script@v1
     with:
       script: |-
         cd /yolov5
         python train.py --workers 4 --name yolo_fraude_detect --img 640 --batch 32 --epochs 100 --data yolo/datasets/labels/train/normal_suspect.yml --weights yolov5s.pt --cfg yolo/config/custum_yolov5s.yaml
       image: tensorflow/tensorflow:1.14.0-gpu-py3


#  exportModel:
#    resources:
#      instance-type: C4
#    needs:
#      - trainModel
#    inputs:
#      repo: cloneYOLO.outputs.repo
#      ckpt: trainModel.outputs.checkPoints
#
#    outputs:
#      exportedModel:
#        type: dataset
#        with:
#          ref: yolo-exported-model
#    uses: script@v1
#    with:
#      script: |-
#        cd /yolov5
#        python export.py  --data 'yolo/datasets/labels/train/normal_suspect.yml' --weights 'yolo/yolov5/runs/train/yolo_fraude_detect8/weights/best.pt' --include tfjs
#      image: tensorflow/tensorflow:1.14.0-gpu-py3